/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 作問 */
        post: operations["create_problem_api_problems_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{problem_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 問題の再取得 */
        get: operations["get_problem_api_problems__problem_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{problem_id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 採点 */
        post: operations["submit_answer_api_problems__problem_id__answers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** サンプル問題の一覧 */
        get: operations["list_samples_api_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 作問数の残り */
        get: operations["get_usage_api_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 死活確認 */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnswerResponse
         * @description 採点結果。モードに応じて transcription か summary の一方だけが入る。
         */
        AnswerResponse: {
            /** Attempt Id */
            attempt_id: string;
            /** Problem Id */
            problem_id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "transcription" | "summary";
            /**
             * Source Text
             * @description 題材の全文（自分の入力と並べて確認するため。要件 F3-3）
             */
            source_text: string;
            /** User Input */
            user_input: string;
            transcription?: components["schemas"]["TranscriptionResult"] | null;
            summary?: components["schemas"]["SummaryResult"] | null;
        };
        /**
         * CreateProblemRequest
         * @description 作問の依頼（要件 F1-1）。
         */
        CreateProblemRequest: {
            /**
             * Theme
             * @description 何について話すか
             * @example IT 企業の株主総会で、社長が四半期の業績を報告する
             */
            theme: string;
            /**
             * Target Length
             * @description 目標文字数
             * @default 300
             */
            target_length: number;
            /**
             * Info
             * @description 追加の指示（任意）
             * @default
             * @example 専門用語を少し含める
             */
            info: string;
            /**
             * Mode
             * @description 採点モード
             * @default transcription
             * @enum {string}
             */
            mode: "transcription" | "summary";
        };
        /**
         * DiffSegment
         * @description 正解文と入力文の差分 1 区間。
         *
         *     文字単位ではなく区間単位で返すことで、レスポンスを小さく保つ。
         *     - equal   : 一致（gold == typed）
         *     - replace : 書き換え（gold → typed）
         *     - delete  : 入力側で欠落（typed が空）
         *     - insert  : 入力側の余分（gold が空）
         */
        DiffSegment: {
            /**
             * Op
             * @enum {string}
             */
            op: "equal" | "replace" | "delete" | "insert";
            /**
             * Gold
             * @default
             */
            gold: string;
            /**
             * Typed
             * @default
             */
            typed: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ProblemResponse
         * @description 問題。作問直後と再取得のどちらもこの形で返す。
         *
         *     題材の全文も含める。音声を聞けば分かる情報であり、隠しても訓練上の意味がないため。
         */
        ProblemResponse: {
            /** Problem Id */
            problem_id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "transcription" | "summary";
            /** Theme */
            theme: string;
            /**
             * Text
             * @description 題材の全文
             */
            text: string;
            /**
             * Sentences
             * @description 文ごとのテキストと、音声上の開始位置
             */
            sentences: components["schemas"]["Sentence"][];
            /**
             * Duration Ms
             * @description 音声全体の長さ（ミリ秒）。音声を読み込む前に進行バーを描くため
             */
            duration_ms?: number | null;
            /**
             * Audio Url
             * @description 音声の署名付き URL。期限が切れたら問題を再取得すると新しい URL が得られる
             */
            audio_url: string;
            /**
             * Audio Url Expires At
             * Format: date-time
             */
            audio_url_expires_at: string;
        };
        /**
         * SampleSummary
         * @description サンプル問題の一覧に出す項目。本体は GET /api/problems/{problem_id} で取る。
         */
        SampleSummary: {
            /** Problem Id */
            problem_id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "transcription" | "summary";
            /** Theme */
            theme: string;
            /**
             * Char Count
             * @description 題材の文字数
             */
            char_count: number;
            /** Sentence Count */
            sentence_count: number;
            /**
             * Duration Ms
             * @description 音声全体の長さ（ミリ秒）
             */
            duration_ms?: number | null;
        };
        /**
         * Sentence
         * @description 題材を構成する 1 文と、その音声上の位置。
         */
        Sentence: {
            /**
             * Index
             * @description 先頭からの通し番号
             */
            index: number;
            /** Text */
            text: string;
            /**
             * Start Ms
             * @description 音声のどのミリ秒から読み始めるか
             */
            start_ms: number;
        };
        /**
         * SubmitAnswerRequest
         * @description 回答。どの問題への回答かは URL のパスで示す。
         */
        SubmitAnswerRequest: {
            /**
             * User Input
             * @description 書き取った文章、または要約
             */
            user_input: string;
        };
        /**
         * SummaryResult
         * @description 要約モードの採点結果。
         */
        SummaryResult: {
            /**
             * Score
             * @description 最終スコア
             */
            score: number;
            /**
             * Score Raw
             * @description LLM の素点
             */
            score_raw: number;
            /**
             * Penalty
             * @description 長さによる自動減点
             */
            penalty: number;
            /**
             * Hallucination
             * @description 元文にない内容の付け足しがあるか
             */
            hallucination: boolean;
            subscores: components["schemas"]["SummarySubscores"];
            /** Penalty Reasons */
            penalty_reasons: string[];
            /**
             * Notes
             * @description 採点理由の総評
             */
            notes: string;
            /**
             * Best Summary
             * @description 模範要約
             */
            best_summary: string;
        };
        /**
         * SummarySubscores
         * @description 要約モードの観点別スコア。
         */
        SummarySubscores: {
            /**
             * Faithfulness
             * @description 忠実性
             */
            faithfulness: number;
            /**
             * Coverage
             * @description 網羅性
             */
            coverage: number;
            /**
             * Clarity
             * @description 明瞭・簡潔
             */
            clarity: number;
        };
        /**
         * TranscriptionResult
         * @description 文字起こしモードの採点結果。
         */
        TranscriptionResult: {
            /**
             * Accuracy
             * @description 正答率 (%)
             */
            accuracy: number;
            /**
             * Distance
             * @description 編集距離（誤り文字数）
             */
            distance: number;
            /**
             * Length
             * @description 正規化後の正解文の文字数
             */
            length: number;
            /** Diff */
            diff: components["schemas"]["DiffSegment"][];
        };
        /** UsageCount */
        UsageCount: {
            /** Used */
            used: number;
            /** Limit */
            limit: number;
            /** Remaining */
            remaining: number;
        };
        /** UsageLimitErrorResponse */
        UsageLimitErrorResponse: {
            /** Detail */
            detail: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "daily" | "monthly";
            /** Limit */
            limit: number;
        };
        /**
         * UsageStatus
         * @description 作問数の上限と使用数（要件 N2-3）。上限に達してから知るのではなく、先に見せる。
         */
        UsageStatus: {
            daily: components["schemas"]["UsageCount"];
            monthly: components["schemas"]["UsageCount"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_problem_api_problems_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProblemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 作問数の上限に達した */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageLimitErrorResponse"];
                };
            };
            /** @description 題材の生成に失敗した */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_problem_api_problems__problem_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 問題 ID（16 進 32 文字） */
                problem_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 問題が無い（1 日経つと消える） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_answer_api_problems__problem_id__answers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 問題 ID（16 進 32 文字） */
                problem_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerResponse"];
                };
            };
            /** @description 問題が無い */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 要約の採点回数の上限に達した */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageLimitErrorResponse"];
                };
            };
            /** @description 要約の採点に失敗した */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_samples_api_samples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleSummary"][];
                };
            };
        };
    };
    get_usage_api_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageStatus"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
